### ISSUE TITLE
Plugin creates broken multipolygons

### ISSUE THREAD

**Issue by woodpeck** [jonasstein/scanaerial#20]
I came across a changeset today which reports to have been made with this plugin and which had creted a large number of intersecting inner rings, making the polygon invalid. The changeset is here: https://www.openstreetmap.org/changeset/28939744 - I don't know which version of the software was used and with which settings but I would like to encourage the makers of the plugin to ensure that no such broken geometries are generated.

**Comment by Vort** [comment]
I will investigate this problem.
Probably, this is the result of an incorrect merge of existed and newly created objects.

**Comment by Vort** [comment]
There was not so many problems with this lake: http://goo.gl/fKZmrJ
I have fixed most of them, but was not able to validate my change (because of JOSM hanging)
https://josm.openstreetmap.de/ticket/12169

Concerning intersecting inner rings: what I can say now is that this error comes from incorrect merging of multipolygons by JOSM.

**Comment by Vort** [comment]
Concerning the reasons of inner ring problem:

Big objects, like this lake, hard to process at once.
Better is to split this job and trace big object part by part.
Then parts needs to be merged.

The parts, created by scanaerial don't have inner ring problem.
Problem appears after merge action executed in JOSM.
Then it gets to server, because JOSM validation do not alarms user about this particular problem.

**Comment by Vort** [comment]
Now JOSM is not hangs with validation of big multipolygons and it is possible to check for inner ring intersections before submitting your data to server.
Also, lake object is fixed, so I am closing this report.
