### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'dict_items' and 'list'

### ISSUE THREAD

**Issue by nikh1ll** [jonasstein/scanaerial#21]
Hi, I was trying to use Scanaerial. After setting it up I tried running but getting the below error:

``` /home/nikhil/.josm/plugins/ext_tools/scanaerial/scanaerial.py {39.0512} {-78.1512} 20.0 
this program expects latitude longitude, now running debug mode
Traceback (most recent call last):
  File "/home/nikhil/.josm/plugins/ext_tools/scanaerial/scanaerial.py", line 122, in <module>
    WAY_TAGS = dict(WAY_TAGS.items() + config.items('TAGS'))
TypeError: unsupported operand type(s) for +: 'dict_items' and 'list'
```

While doing the Library check I also get this error message:

![screenshot from 2016-11-29 00-06-18](https://cloud.githubusercontent.com/assets/11845908/20681028/af970526-b5c7-11e6-8830-25e4cd2866ef.png)

System: Manjaro (Arch) Linux.
JOSM Version: 11223

It would be great if you could help me with this @jonasstein.

**Comment by Vort** [comment]
I see 3 possible sources of problems:
1. On your screenshot coordinates enclosed with brackets. This is incorrect. Try to invoke scanaerial manually, without JOSM. ```python scanaerial.py 73.4146114 87.2258663```
2. Maybe something wrong with configuration file.
3. Maybe incorrect version of Python is used.

**Comment by nikhilprabhakar** [comment]
> 1. On your screenshot coordinates enclosed with brackets. This is incorrect. Try to invoke >Scanaerial manually, without JOSM. python scanaerial.py 73.4146114 87.2258663

- I was not entirely sure how to work with Scanaerial which is why JOSM was used by me.
I will try to invoke Scanaerial manually and will share the output.

> 2. Maybe something wrong with the configuration file.

- I have used the default configuration without making any changes.

> 3. Maybe the incorrect version of Python is used. 

- I have installed python2 which was required and all the other required packages. As you can see from the below pic the dependencies packs seem to be recognized by Scanaerial when doing the `library check`.
![screen shot 2016-11-29 at 11 14 07 am](https://cloud.githubusercontent.com/assets/11845908/20698183/35eb804a-b625-11e6-98da-2c64fd76ab66.png)

Thanks a lot for the reply @Vort. I will dig into this issue more and share the output once I am off from work.

**Comment by Vort** [comment]
> I have installed python2 which was required and all the other required packages.

Maybe you installed Python 2.7, but another version is still used by default?
Try ```python --version``` command.

**Comment by Vort** [comment]
@nikhilprabhakar, is there any progress on this problem?

**Comment by taranarmo** [comment]
I had the same issue, and I was able to workaround it:
You probably have python3 also installed and it is used by default. Add python2 at the begining of the cmd. This action fixed the problem, at least in Arch (Manjaro actually)

**Comment by nikh1ll** [comment]
@taranarmo - I was trying it in Manjaro! Thanks for the response. I am going to close this for now.
